Make kubeconfig path dynamic
mkfdoherty/redis pull request #4
Opened 2020-10-21 14:36 UTC by phkunt

2020-10-21 17:34 UTC, mkfdoherty requested changes

2020-10-21 17:34 UTC, mkfdoherty commented on controllers/redis_controller.go
> +var home, _ = os.UserHomeDir()
What about something like this?

```suggestion
func findKubeConfig() (string, error) {
	env := os.Getenv("KUBECONFIG")
	if env != "" {
		return env, nil
	}
	path, err := homedir.Expand("~/.kube/config")
	if err != nil {
		return "", err
	}
	return path, nil
}
```

2020-10-21 17:40 UTC, phkunt commented on controllers/redis_controller.go
> +var home, _ = os.UserHomeDir()
This is probably the better way to do it. Then the user has the option to either pass the config file as an env-variable or use the "default" path.

2020-10-21 17:52 UTC, phkunt commented on controllers/redis_controller.go
> +var home, _ = os.UserHomeDir()
Since the kubeConfigPath variable is declared outside of a function, where would it then make sense to check for the return of the findKubeConfig() function?

2020-10-25 16:08 UTC, closed without merging

2020-10-25 16:20 UTC, mkfdoherty commented
@phkunt I ended up doing it like this

https://github.com/mkfdoherty/redis/pull/6